version: '3'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    expose:
      - 5432

  nginx:
    image: nginx
    volumes:
      - ./configs/nginx:/etc/nginx/templates
    ports:
      - 80:80

  example-metrics:
    image: adoptopenjdk:8u252-b09-jre-openj9-0.20.0-bionic
#    depends_on:
#      - db
    volumes:
      - ./target/pack:/usr/apps/example-metrics
    command: /usr/apps/example-metrics/bin/hello
    ports:
      - 8080:8080

#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"
#
#  influxdb:
#    image: influxdb
#    ports:
#      - "8086:8086"
#
#  telegraf:
#    image: telegraf
#    depends_on:
#      - influxdb
