version: '3'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - backend

  nginx:
    image: nginx
    volumes:
      - ./configs/nginx:/etc/nginx/templates
    ports:
      - 80:80
    networks:
      - backend
      - metrics

  example-metrics:
    image: adoptopenjdk:8u252-b09-jre-openj9-0.20.0-bionic
    volumes:
      - ./target/pack:/usr/apps/example-metrics
    command: /usr/apps/example-metrics/bin/hello
    networks:
      - backend

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - metrics

  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    networks:
      - metrics

  telegraf:
    image: telegraf
    volumes:
      - ./configs/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - metrics

networks:
  backend:
  metrics:
